#ifndef BBIOCONFIG_GLOBAL_H
#define BBIOCONFIG_GLOBAL_H

#include <QtGlobal>

#if defined(BBIOCONFIG_LIBRARY)
#  define BBIOCONFIGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BBIOCONFIGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BBIOCONFIG_GLOBAL_H

